import { EDUCATION_GROUP, type StaffSeed } from "./staff-types";

const T = EDUCATION_GROUP;

export const OFFICIAL_STAFF: StaffSeed[] = [
  {
    teacherCode: "551703",
    fullName: "هدى عبدالله يوسف هاشم",
    nationalId: "27109240104524",
    appointmentDate: "1991-09-01",
    subject: "مدرس رياض أطفال",
    financialGrade: "معلم خبير",
    financialGradeDate: "2008-07-01",
    jobGroup: T,
    currentJob: "معلم خبير",
    qualificationType: "عليا",
    qualification: "ليسانس آداب وتربية",
    cadreJob: "معلم خبير",
    cadreDate: "2022-10-19",
    schoolCode: "kg",
    category: "معلم",
    underCadre: true,
  },
  {
    teacherCode: "551766",
    fullName: "ابتسام احمد عثمان على",
    nationalId: "27111051400745",
    appointmentDate: "1991-11-01",
    subject: "لغة عربية ودين",
    financialGrade: "معلم خبير",
    financialGradeDate: "2008-07-01",
    jobGroup: T,
    currentJob: "معلم خبير",
    qualificationType: "فوق المتوسطة",
    qualification: "دبلوم المعلمين والمعلمات",
    cadreJob: "معلم خبير",
    cadreDate: "2022-10-19",
    schoolCode: "primary",
    category: "معلم",
    underCadre: true,
  },
  {
    teacherCode: "2694407",
    fullName: "اميره جوده عبدالخالق عطيه",
    nationalId: "28505010400082",
    appointmentDate: "2015-06-16",
    subject: "لغة عربية ودين",
    financialGrade: "معلم أول",
    financialGradeDate: "2015-06-16",
    jobGroup: T,
    currentJob: "معلم أول",
    qualificationType: "عليا",
    qualification: "ليسانس آداب وتربية",
    cadreJob: "معلم أول",
    cadreDate: "2026-07-06",
    schoolCode: "primary",
    category: "معلم",
    underCadre: true,
  },
  {
    teacherCode: "2714820",
    fullName: "ايمان طلال سعدالدين زغلول",
    nationalId: "28607070400321",
    appointmentDate: "2014-06-16",
    subject: "دراسات اجتماعية",
    financialGrade: "معلم أول",
    financialGradeDate: "2014-06-16",
    jobGroup: T,
    currentJob: "معلم أول",
    qualificationType: "عليا",
    qualification: "ليسانس آداب وتربية",
    cadreJob: "معلم أول",
    cadreDate: "2022-10-19",
    schoolCode: "primary",
    category: "معلم",
    underCadre: true,
  },
  {
    teacherCode: "553098",
    fullName: "ايمان عبدالسميع محمد الغرب",
    nationalId: "27312110101167",
    appointmentDate: "1995-09-01",
    subject: "لغة إنجليزية",
    financialGrade: "كبير معلمين",
    financialGradeDate: "2005-01-01",
    jobGroup: T,
    currentJob: "كبير معلمين",
    qualificationType: "عليا",
    qualification: "ليسانس آداب وتربية",
    cadreJob: "كبير معلمين",
    cadreDate: "2025-02-03",
    schoolCode: "primary",
    category: "معلم",
    underCadre: true,
  },
  {
    teacherCode: "551142",
    fullName: "جهان سيد محمد محمود",
    nationalId: "27011012201781",
    appointmentDate: "1990-10-16",
    subject: "مدرس فصل",
    financialGrade: "معلم خبير",
    financialGradeDate: "2008-07-01",
    jobGroup: T,
    currentJob: "معلم خبير",
    qualificationType: "فوق المتوسطة",
    qualification: "دبلوم المعلمين والمعلمات",
    cadreJob: "معلم خبير",
    cadreDate: "2022-10-19",
    schoolCode: "primary",
    category: "معلم",
    underCadre: true,
  },
  {
    teacherCode: "1778261",
    fullName: "حنان محمد على ابراهيم",
    nationalId: "26702270400101",
    appointmentDate: "1987-05-01",
    subject: "تربية موسيقية",
    financialGrade: "معلم خبير",
    financialGradeDate: "2008-07-01",
    jobGroup: T,
    currentJob: "معلم خبير",
    qualificationType: "فوق المتوسطة",
    qualification: "دبلوم المعلمين والمعلمات",
    cadreJob: "معلم خبير",
    cadreDate: "2022-10-19",
    schoolCode: "primary",
    category: "معلم",
    underCadre: true,
  },
  {
    teacherCode: "549418",
    fullName: "سهير حسن السيد احمد",
    nationalId: "26709232601644",
    appointmentDate: "1988-11-01",
    subject: "مدرس فصل",
    financialGrade: "معلم خبير",
    financialGradeDate: "2008-07-01",
    jobGroup: T,
    currentJob: "معلم خبير",
    qualificationType: "فوق المتوسطة",
    qualification: "دبلوم الدراسات التكميلية الصناعية",
    cadreJob: "معلم خبير",
    cadreDate: "2022-10-19",
    schoolCode: "primary",
    category: "معلم",
    underCadre: true,
  },
  {
    teacherCode: "552803",
    fullName: "عبدالله الحسنى محمد احمد",
    nationalId: "27305252100536",
    appointmentDate: "1996-06-30",
    subject: "",
    financialGrade: "الأولى - أ",
    financialGradeDate: "2019-07-01",
    jobGroup: "الوظائف الفنية للتعليم",
    currentJob: "مشرف (أ) مواد / نشاط",
    qualificationType: "متوسطة",
    qualification: "دبلوم صناعة ثانوي",
    cadreJob: "غير مخاطب حاليا بقانون كادر المعلم",
    cadreDate: "",
    schoolCode: "primary",
    category: "مشرف نشاط",
    underCadre: false,
  },
  {
    teacherCode: "2861165",
    fullName: "علاء سعد على كريم",
    nationalId: "28901100400157",
    appointmentDate: "2013-02-13",
    subject: "",
    financialGrade: "الثالثة - أ",
    financialGradeDate: "2024-07-01",
    jobGroup: "الوظائف الفنية للتعليم",
    currentJob: "مشرف نشاط / خدمات",
    qualificationType: "متوسطة",
    qualification: "دبلوم الثانوى الفنى للصم وضعاف السمع",
    cadreJob: "غير مخاطب حاليا بقانون كادر المعلم",
    cadreDate: "",
    schoolCode: "primary",
    category: "مشرف نشاط",
    underCadre: false,
  },
  {
    teacherCode: "549801",
    fullName: "محمد محمود ابراهيم سيد احمد",
    nationalId: "26710010400258",
    appointmentDate: "1987-11-01",
    subject: "رياضيات",
    financialGrade: "معلم خبير",
    financialGradeDate: "2008-07-01",
    jobGroup: T,
    currentJob: "معلم خبير",
    qualificationType: "متوسطة",
    qualification: "دبلوم معلمين ومعلمات",
    cadreJob: "معلم خبير",
    cadreDate: "2022-10-19",
    schoolCode: "primary",
    category: "معلم",
    underCadre: true,
  },
  {
    teacherCode: "554811",
    fullName: "محمد مصطفى محمد احمد",
    nationalId: "27902200400491",
    appointmentDate: "1999-01-16",
    subject: "",
    financialGrade: "الأولى - أ",
    financialGradeDate: "2019-07-01",
    jobGroup: "المجموعة الفنية لوظائف الهندسة",
    currentJob: "فنى صيانة أول",
    qualificationType: "فوق المتوسطة",
    qualification: "دبلوم الدراسات التكميلية الصناعية",
    cadreJob: "غير مخاطب حاليا بقانون كادر المعلم",
    cadreDate: "",
    schoolCode: "primary",
    category: "فني صيانة",
    underCadre: false,
  },
  {
    teacherCode: "2735023",
    fullName: "اميره محمد عبدالحميد اسماعيل",
    nationalId: "28712090400181",
    appointmentDate: "2014-06-16",
    subject: "لغة عربية ودين",
    financialGrade: "معلم أول",
    financialGradeDate: "2014-06-16",
    jobGroup: T,
    currentJob: "معلم أول",
    qualificationType: "عليا",
    qualification: "ليسانس آداب وتربية",
    cadreJob: "معلم أول",
    cadreDate: "2022-10-19",
    schoolCode: "primary",
    category: "معلم",
    underCadre: true,
  },
  {
    teacherCode: "551083",
    fullName: "منال عباس محمد على",
    nationalId: "27009240100389",
    appointmentDate: "1990-10-16",
    subject: "لغة عربية ودين",
    financialGrade: "معلم خبير",
    financialGradeDate: "2008-07-01",
    jobGroup: T,
    currentJob: "معلم خبير",
    qualificationType: "عليا",
    qualification: "ليسانس آداب وتربية",
    cadreJob: "معلم خبير",
    cadreDate: "2022-10-19",
    schoolCode: "primary",
    category: "معلم",
    underCadre: true,
  },
  {
    teacherCode: "550462",
    fullName: "مرفت فتحى محمد ابراهيم جبريل",
    nationalId: "26909181300261",
    appointmentDate: "1989-09-01",
    subject: "مدرس فصل",
    financialGrade: "معلم خبير",
    financialGradeDate: "2008-07-01",
    jobGroup: T,
    currentJob: "معلم خبير",
    qualificationType: "فوق المتوسطة",
    qualification: "دبلوم المعلمين والمعلمات",
    cadreJob: "معلم خبير",
    cadreDate: "2022-10-19",
    schoolCode: "primary",
    category: "معلم",
    underCadre: true,
  },
  {
    teacherCode: "2861179",
    fullName: "ناهد صبرى عبدالله مصطفى",
    nationalId: "28509121300589",
    appointmentDate: "2013-02-13",
    subject: "",
    financialGrade: "الثالثة - أ",
    financialGradeDate: "2024-07-01",
    jobGroup: "الوظائف الفنية للتعليم",
    currentJob: "مشرف نشاط / خدمات",
    qualificationType: "متوسطة",
    qualification: "دبلوم الثانوى الفنى للصم وضعاف السمع",
    cadreJob: "غير مخاطب حاليا بقانون كادر المعلم",
    cadreDate: "",
    schoolCode: "primary",
    category: "مشرف نشاط",
    underCadre: false,
  },
  {
    teacherCode: "2352074",
    fullName: "هبه محمد قنديل محمد",
    nationalId: "28511070400341",
    appointmentDate: "2011-08-04",
    subject: "",
    financialGrade: "معلم أول أ",
    financialGradeDate: "2011-08-04",
    jobGroup: T,
    currentJob: "أخصائي صحافة وإعلام أول أ",
    qualificationType: "دراسات عليا",
    qualification: "دبلوم عام فى التربية",
    cadreJob: "أخصائي صحافة وإعلام أول أ",
    cadreDate: "2023-08-17",
    schoolCode: "primary",
    category: "أخصائي صحافة وإعلام",
    underCadre: true,
  },
  {
    teacherCode: "2063734",
    fullName: "هدى فوزى سيد علام",
    nationalId: "28505130400248",
    appointmentDate: "2008-03-01",
    subject: "لغة إنجليزية",
    financialGrade: "معلم أول أ",
    financialGradeDate: "2008-03-01",
    jobGroup: T,
    currentJob: "معلم أول أ",
    qualificationType: "عليا",
    qualification: "ليسانس آداب وتربية",
    cadreJob: "معلم أول أ",
    cadreDate: "2023-08-17",
    schoolCode: "primary",
    category: "معلم",
    underCadre: true,
  },
  {
    teacherCode: "548966",
    fullName: "الهام محمود محمد حسن",
    nationalId: "26611140400049",
    appointmentDate: "1990-11-01",
    subject: "رياضيات",
    financialGrade: "كبير معلمين",
    financialGradeDate: "2005-01-01",
    jobGroup: T,
    currentJob: "كبير معلمين",
    qualificationType: "عليا",
    qualification: "بكالوريوس علوم وتربية",
    cadreJob: "كبير معلمين",
    cadreDate: "2018-10-08",
    schoolCode: "prep",
    category: "معلم",
    underCadre: true,
  },
  {
    teacherCode: "554361",
    fullName: "امانى عزت سامى توفيق",
    nationalId: "27612100400305",
    appointmentDate: "2000-08-20",
    subject: "لغة إنجليزية",
    financialGrade: "معلم خبير",
    financialGradeDate: "2010-07-01",
    jobGroup: T,
    currentJob: "معلم خبير",
    qualificationType: "عليا",
    qualification: "ليسانس آداب وتربية",
    cadreJob: "معلم خبير",
    cadreDate: "2025-02-03",
    schoolCode: "prep",
    category: "معلم",
    underCadre: true,
  },
  {
    teacherCode: "551862",
    fullName: "اميره صالح احمد صالح",
    nationalId: "27112081300181",
    appointmentDate: "1996-12-21",
    subject: "لغة عربية ودين",
    financialGrade: "كبير معلمين",
    financialGradeDate: "2005-01-01",
    jobGroup: T,
    currentJob: "كبير معلمين",
    qualificationType: "عليا",
    qualification: "ليسانس آداب",
    cadreJob: "كبير معلمين",
    cadreDate: "2025-02-03",
    schoolCode: "prep",
    category: "معلم",
    underCadre: true,
  },
  {
    teacherCode: "2720847",
    fullName: "رحاب محمد نورالدين محمد",
    nationalId: "29012230400129",
    appointmentDate: "2012-06-16",
    subject: "لغة عربية ودين",
    financialGrade: "معلم أول",
    financialGradeDate: "2012-06-16",
    jobGroup: T,
    currentJob: "معلم أول",
    qualificationType: "عليا",
    qualification: "ليسانس آداب وتربية",
    cadreJob: "معلم أول",
    cadreDate: "2022-10-19",
    schoolCode: "prep",
    category: "معلم",
    underCadre: true,
  },
  {
    teacherCode: "2843066",
    fullName: "محمد احمد على محمد",
    nationalId: "28911010400218",
    appointmentDate: "2013-02-14",
    subject: "دراسات اجتماعية",
    financialGrade: "معلم أول",
    financialGradeDate: "2013-02-12",
    jobGroup: T,
    currentJob: "معلم أول",
    qualificationType: "عليا",
    qualification: "ليسانس آداب وحاصل على برنامج التأهيل التربوي",
    cadreJob: "معلم أول",
    cadreDate: "2023-08-17",
    schoolCode: "prep",
    category: "معلم",
    underCadre: true,
  },
  {
    teacherCode: "2850173",
    fullName: "محمد حسين احمد حسين",
    nationalId: "28701010400531",
    appointmentDate: "2013-02-13",
    subject: "",
    financialGrade: "الثالثة - أ",
    financialGradeDate: "2024-07-01",
    jobGroup: "المجموعة النوعية لوظائف المكتبية",
    currentJob: "كاتب ثالث - سكرتير ثالث",
    qualificationType: "متوسطة",
    qualification: "ثانوية عامة",
    cadreJob: "غير مخاطب حاليا بقانون كادر المعلم",
    cadreDate: "",
    schoolCode: "prep",
    category: "إداري",
    underCadre: false,
  },
  {
    teacherCode: "2843070",
    fullName: "مصطفى على محمد محمود",
    nationalId: "28902060400279",
    appointmentDate: "2013-02-13",
    subject: "دراسات اجتماعية",
    financialGrade: "معلم أول",
    financialGradeDate: "2013-02-12",
    jobGroup: T,
    currentJob: "معلم أول",
    qualificationType: "عليا",
    qualification: "ليسانس آداب وحاصل على برنامج التأهيل التربوي",
    cadreJob: "معلم أول",
    cadreDate: "2023-08-17",
    schoolCode: "prep",
    category: "معلم",
    underCadre: true,
  },
  {
    teacherCode: "553056",
    fullName: "ناصر محمد نورالدين همام",
    nationalId: "27311220104319",
    appointmentDate: "2000-08-20",
    subject: "",
    financialGrade: "معلم خبير",
    financialGradeDate: "2000-08-20",
    jobGroup: T,
    currentJob: "أمين مكتبة خبير - وكيل مدرسة",
    qualificationType: "عليا",
    qualification: "ليسانس آداب وتربية",
    cadreJob: "أمين مكتبة خبير - وكيل مدرسة",
    cadreDate: "2025-02-03",
    schoolCode: "prep",
    category: "وكيل مدرسة",
    underCadre: true,
  },
  {
    teacherCode: "553710",
    fullName: "هشام فؤاد على عبدالباسط",
    nationalId: "27501012601019",
    appointmentDate: "2000-08-20",
    subject: "",
    financialGrade: "معلم خبير",
    financialGradeDate: "2000-08-20",
    jobGroup: T,
    currentJob: "أخصائي اجتماعي خبير",
    qualificationType: "عليا",
    qualification: "بكالوريوس خدمة اجتماعية وحاصل على برنامج التأهيل التربوي",
    cadreJob: "أخصائي اجتماعي خبير",
    cadreDate: "2025-02-03",
    schoolCode: "prep",
    category: "أخصائي اجتماعي",
    underCadre: true,
  },
  {
    teacherCode: "977892",
    fullName: "احمد حسين احمد عبد الله",
    nationalId: "27603141301851",
    appointmentDate: "2000-09-17",
    subject: "رياضيات",
    financialGrade: "معلم خبير",
    financialGradeDate: "2000-09-17",
    jobGroup: T,
    currentJob: "معلم خبير",
    qualificationType: "عليا",
    qualification: "بكالوريوس علوم وتربية",
    cadreJob: "معلم خبير",
    cadreDate: "2026-06-17",
    schoolCode: "secondary",
    category: "معلم",
    underCadre: true,
  },
  {
    teacherCode: "551570",
    fullName: "اسرار محمد ابراهيم بوله",
    nationalId: "27107230105643",
    appointmentDate: "1993-09-01",
    subject: "لغة عربية ودين",
    financialGrade: "كبير معلمين",
    financialGradeDate: "2008-07-01",
    jobGroup: T,
    currentJob: "كبير معلمين",
    qualificationType: "عليا",
    qualification: "ليسانس آداب وتربية",
    cadreJob: "كبير معلمين",
    cadreDate: "2022-10-19",
    schoolCode: "secondary",
    category: "معلم",
    underCadre: true,
  },
  {
    teacherCode: "549667",
    fullName: "السيد عبد المجيد السيد سند",
    nationalId: "26802241100232",
    appointmentDate: "1992-06-24",
    subject: "لغة عربية ودين",
    financialGrade: "كبير معلمين",
    financialGradeDate: "2008-07-01",
    jobGroup: T,
    currentJob: "كبير معلمين",
    qualificationType: "عليا",
    qualification: "ليسانس دار العلوم",
    cadreJob: "كبير معلمين",
    cadreDate: "2022-10-19",
    schoolCode: "secondary",
    category: "معلم",
    underCadre: true,
  },
  {
    teacherCode: "2076039",
    fullName: "اميمة السيد اسماعيل على",
    nationalId: "26904172300086",
    appointmentDate: "1992-09-01",
    subject: "لغة إنجليزية",
    financialGrade: "كبير معلمين",
    financialGradeDate: "2008-07-01",
    jobGroup: T,
    currentJob: "كبير معلمين",
    qualificationType: "عليا",
    qualification: "ليسانس آداب وتربية",
    cadreJob: "كبير معلمين",
    cadreDate: "2022-10-19",
    schoolCode: "secondary",
    category: "معلم",
    underCadre: true,
  },
  {
    teacherCode: "2495572",
    fullName: "رائدا محمد محمود غريب",
    nationalId: "28010200400144",
    appointmentDate: "2018-04-22",
    subject: "",
    financialGrade: "الثالثة - ج",
    financialGradeDate: "2024-07-01",
    jobGroup: "المجموعة النوعية فنى معامل",
    currentJob: "فنى ثالث",
    qualificationType: "متوسطة",
    qualification: "دبلوم صناعة ثانوى",
    cadreJob: "غير مخاطب حاليا بقانون كادر المعلم",
    cadreDate: "2025-02-03",
    schoolCode: "secondary",
    category: "فني معامل",
    underCadre: false,
  },
  {
    teacherCode: "551243",
    fullName: "سهاد محمد الشعرواي عبدالمعطي عبدالهادى",
    nationalId: "27012100104041",
    appointmentDate: "1997-06-10",
    subject: "",
    financialGrade: "كبير معلمين",
    financialGradeDate: "2006-07-01",
    jobGroup: T,
    currentJob: "كبير أخصائيين اجتماعيين",
    qualificationType: "عليا",
    qualification: "بكالوريوس خدمة اجتماعية وحاصل على برنامج التأهيل التربوي",
    cadreJob: "كبير أخصائيين اجتماعيين",
    cadreDate: "2025-02-03",
    schoolCode: "secondary",
    category: "أخصائي اجتماعي",
    underCadre: true,
  },
  {
    teacherCode: "2213465",
    fullName: "شيماء فؤاد محمد السيد",
    nationalId: "28106300400181",
    appointmentDate: "2005-07-17",
    subject: "علم نفس واجتماع",
    financialGrade: "معلم أول أ",
    financialGradeDate: "2011-08-04",
    jobGroup: T,
    currentJob: "معلم أول أ",
    qualificationType: "عليا",
    qualification: "ليسانس آداب وتربية",
    cadreJob: "معلم أول أ",
    cadreDate: "2023-08-17",
    schoolCode: "secondary",
    category: "معلم",
    underCadre: true,
  },
  {
    teacherCode: "553872",
    fullName: "عبدالعزيز كامل خضير محمد",
    nationalId: "27504120400053",
    appointmentDate: "2000-08-20",
    subject: "",
    financialGrade: "معلم خبير",
    financialGradeDate: "2000-05-22",
    jobGroup: T,
    currentJob: "أمين مكتبة خبير",
    qualificationType: "عليا",
    qualification: "ليسانس آداب",
    cadreJob: "أمين مكتبة خبير",
    cadreDate: "2025-02-03",
    schoolCode: "secondary",
    category: "أمين مكتبة",
    underCadre: true,
  },
  {
    teacherCode: "553894",
    fullName: "محمد جابر زكي على",
    nationalId: "27504150400112",
    appointmentDate: "1999-01-16",
    subject: "لغة فرنسية",
    financialGrade: "معلم خبير",
    financialGradeDate: "2008-07-01",
    jobGroup: T,
    currentJob: "معلم خبير",
    qualificationType: "عليا",
    qualification: "ليسانس آداب وتربية",
    cadreJob: "معلم خبير",
    cadreDate: "2022-10-19",
    schoolCode: "secondary",
    category: "معلم",
    underCadre: true,
  },
  {
    teacherCode: "554333",
    fullName: "محمد سيد حسين رضوان",
    nationalId: "27610120100658",
    appointmentDate: "2000-08-20",
    subject: "تاريخ",
    financialGrade: "معلم خبير",
    financialGradeDate: "2000-08-20",
    jobGroup: T,
    currentJob: "معلم خبير",
    qualificationType: "عليا",
    qualification: "ليسانس آداب وحاصل على برنامج التأهيل التربوي",
    cadreJob: "معلم خبير",
    cadreDate: "2025-02-03",
    schoolCode: "secondary",
    category: "معلم",
    underCadre: true,
  },
  {
    teacherCode: "551590",
    fullName: "محمد على خليل عبدالعال",
    nationalId: "27107082100319",
    appointmentDate: "2000-08-20",
    subject: "حاسب آلى متفرغ",
    financialGrade: "معلم خبير",
    financialGradeDate: "2012-05-22",
    jobGroup: T,
    currentJob: "معلم خبير",
    qualificationType: "عليا",
    qualification: "بكالوريوس تجارة وحاصل على برنامج التأهيل التربوي",
    cadreJob: "معلم خبير",
    cadreDate: "2025-02-03",
    schoolCode: "secondary",
    category: "معلم",
    underCadre: true,
  },
  {
    teacherCode: "549228",
    fullName: "مصطفى سليمان سعيد محمد",
    nationalId: "26705063100058",
    appointmentDate: "1990-11-01",
    subject: "رياضيات",
    financialGrade: "كبير معلمين",
    financialGradeDate: "2005-01-01",
    jobGroup: T,
    currentJob: "كبير معلمين",
    qualificationType: "عليا",
    qualification: "بكالوريوس علوم وتربية",
    cadreJob: "كبير معلمين",
    cadreDate: "2018-10-08",
    schoolCode: "secondary",
    category: "معلم",
    underCadre: true,
  },
  {
    teacherCode: "2915059",
    fullName: "منار محمد نورالدين محمد",
    nationalId: "28805202100965",
    appointmentDate: "2012-06-16",
    subject: "جغرافيا",
    financialGrade: "معلم أول",
    financialGradeDate: "2012-06-16",
    jobGroup: T,
    currentJob: "معلم أول",
    qualificationType: "عليا",
    qualification: "ليسانس آداب وتربية",
    cadreJob: "معلم أول",
    cadreDate: "2022-10-19",
    schoolCode: "secondary",
    category: "معلم",
    underCadre: true,
  },
  {
    teacherCode: "2915532",
    fullName: "ناديه عبد المجيد عباس عبد المجيد",
    nationalId: "27601292400123",
    appointmentDate: "1996-01-12",
    subject: "",
    financialGrade: "الأولى أ",
    financialGradeDate: "2019-07-01",
    jobGroup: "المجموعة النوعية لوظائف المكتبية",
    currentJob: "معاون أول",
    qualificationType: "متوسطة",
    qualification: "دبلوم صناعة ثانوي",
    cadreJob: "غير مخاطب حاليا بقانون كادر المعلم",
    cadreDate: "",
    schoolCode: "secondary",
    category: "إداري",
    underCadre: false,
  },
  {
    teacherCode: "2294358",
    fullName: "نجلاء سيد بشارى سيد",
    nationalId: "27707010110228",
    appointmentDate: "2008-02-17",
    subject: "الفلسفة والمنطق",
    financialGrade: "معلم أول أ",
    financialGradeDate: "2008-02-17",
    jobGroup: T,
    currentJob: "معلم أول أ",
    qualificationType: "عليا",
    qualification: "ليسانس آداب وتربية",
    cadreJob: "معلم أول أ",
    cadreDate: "2023-08-17",
    schoolCode: "secondary",
    category: "معلم",
    underCadre: true,
  },
  {
    teacherCode: "2201673",
    fullName: "هبه الله سيف الدين عبدالله حسن",
    nationalId: "28403292102022",
    appointmentDate: "2009-04-15",
    subject: "أحياء",
    financialGrade: "معلم أول أ",
    financialGradeDate: "2009-04-15",
    jobGroup: T,
    currentJob: "معلم أول أ",
    qualificationType: "عليا",
    qualification: "بكالوريوس علوم وتربية",
    cadreJob: "معلم أول أ",
    cadreDate: "2023-08-17",
    schoolCode: "secondary",
    category: "معلم",
    underCadre: true,
  },
];
