/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppPrintRouteImport } from './routes/_app/print'
import { Route as AppQueriesRouteImport } from './routes/_app/queries'
import { Route as AppReportsRouteImport } from './routes/_app/reports'
import { Route as AppStaffIndexRouteImport } from './routes/_app/staff/index'
import { Route as AppStaffIdRouteImport } from './routes/_app/staff/$id'
import { Route as AppStaffNewRouteImport } from './routes/_app/staff/new'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppPrintRoute = AppPrintRouteImport.update({
  id: '/print',
  path: '/print',
  getParentRoute: () => AppRoute,
} as any)
const AppQueriesRoute = AppQueriesRouteImport.update({
  id: '/queries',
  path: '/queries',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppStaffIndexRoute = AppStaffIndexRouteImport.update({
  id: '/staff/',
  path: '/staff/',
  getParentRoute: () => AppRoute,
} as any)
const AppStaffIdRoute = AppStaffIdRouteImport.update({
  id: '/staff/$id',
  path: '/staff/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppStaffNewRoute = AppStaffNewRouteImport.update({
  id: '/staff/new',
  path: '/staff/new',
  getParentRoute: () => AppRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/print': typeof AppPrintRoute
  '/queries': typeof AppQueriesRoute
  '/reports': typeof AppReportsRoute
  '/staff/$id': typeof AppStaffIdRoute
  '/staff/new': typeof AppStaffNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/staff/': typeof AppStaffIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/print': typeof AppPrintRoute
  '/queries': typeof AppQueriesRoute
  '/reports': typeof AppReportsRoute
  '/': typeof AppIndexRoute
  '/staff/$id': typeof AppStaffIdRoute
  '/staff/new': typeof AppStaffNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/staff': typeof AppStaffIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/print': typeof AppPrintRoute
  '/_app/queries': typeof AppQueriesRoute
  '/_app/reports': typeof AppReportsRoute
  '/_app/': typeof AppIndexRoute
  '/_app/staff/$id': typeof AppStaffIdRoute
  '/_app/staff/new': typeof AppStaffNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_app/staff/': typeof AppStaffIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/print'
    | '/queries'
    | '/reports'
    | '/staff/$id'
    | '/staff/new'
    | '/api/auth/$'
    | '/staff/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/print'
    | '/queries'
    | '/reports'
    | '/'
    | '/staff/$id'
    | '/staff/new'
    | '/api/auth/$'
    | '/staff'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/print'
    | '/_app/queries'
    | '/_app/reports'
    | '/_app/'
    | '/_app/staff/$id'
    | '/_app/staff/new'
    | '/api/auth/$'
    | '/_app/staff/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/print': {
      id: '/_app/print'
      path: '/print'
      fullPath: '/print'
      preLoaderRoute: typeof AppPrintRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/queries': {
      id: '/_app/queries'
      path: '/queries'
      fullPath: '/queries'
      preLoaderRoute: typeof AppQueriesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/staff/': {
      id: '/_app/staff/'
      path: '/staff'
      fullPath: '/staff/'
      preLoaderRoute: typeof AppStaffIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/staff/$id': {
      id: '/_app/staff/$id'
      path: '/staff/$id'
      fullPath: '/staff/$id'
      preLoaderRoute: typeof AppStaffIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/staff/new': {
      id: '/_app/staff/new'
      path: '/staff/new'
      fullPath: '/staff/new'
      preLoaderRoute: typeof AppStaffNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppPrintRoute: typeof AppPrintRoute
  AppQueriesRoute: typeof AppQueriesRoute
  AppReportsRoute: typeof AppReportsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppStaffIdRoute: typeof AppStaffIdRoute
  AppStaffNewRoute: typeof AppStaffNewRoute
  AppStaffIndexRoute: typeof AppStaffIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppPrintRoute: AppPrintRoute,
  AppQueriesRoute: AppQueriesRoute,
  AppReportsRoute: AppReportsRoute,
  AppIndexRoute: AppIndexRoute,
  AppStaffIdRoute: AppStaffIdRoute,
  AppStaffNewRoute: AppStaffNewRoute,
  AppStaffIndexRoute: AppStaffIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
